### ISSUE TITLE
Remove gas fee ?

### ISSUE THREAD

**Issue by lucas-goldner** [AymericNoel/First_NFT_Dapp#2]
Hey first thank you for this project, it is really helping me out here.
I would like to know is there a way to create the NFTs without paying the 0,1 ETH. 
Like on Opensea where you can create the NFTs without paying, so they are existing but not minted ?
Thanks a bunch in advance.

**Comment by AymericNoel** [comment]
Hey ! Thanks !
So first, if the tokens are not minted, they cannot exists because they're not onchain. Then, if we change the smart contracts to remove the 0.1 ETH per NFT, it's possible to mint them almost for free ! (The gas fees of ethereum are required but they're not over 1$ I think)

**Comment by lucas-goldner** [comment]
Ok I understand so where do I need to exactly remove the 0.1 per ETH ? 

I tried yesterday myself by changing the network of deployment to matic first where the gas fees are extemly low. Compiled the contracts with truffle and replaced the content of the erc721.json with the newly compiled myContract, but I saw that almost nothing changed really so I am not sure if that made a change, because I want to deploy them on the main net of opensea or matic and not rinkeby or any test network. So could you maybe tell me how I could do this exactly with making the gas fee as low as possible ?

**Comment by AymericNoel** [comment]
Here you need to remove this [line](https://github.com/AymericNoel/First_NFT_Dapp/blob/f968ab04119b78375d3afaa4e249284579c95e65/smart_contract/contracts/MyContract.sol#L20) , this `require` force the user to send a minimum of 0.1 eth. 
I have never deployed contracts on matic or opensea, so if this trick doesn't work, not sure to be able to help....

**Comment by lucas-goldner** [comment]
Oh thanks a bunch I am going to try that

**Comment by lucas-goldner** [comment]
Ok removing the minimum of 0.1 ETH worked thx, but is there like any config I can change in the frontend so it will won't be deployed to rinkeby but instead to matic ? I changed the config in the backend and compiled it again, but I am not sure if that changed something

**Comment by AymericNoel** [comment]
Not sure about that but if you change the network `[here](https://github.com/AymericNoel/First_NFT_Dapp/blob/master/smart_contract/truffle-config.js)` for matic network the front should adapt itself to the same network on metamask

**Comment by lucas-goldner** [comment]
Ah I see is it possible to deploy a NFT only from the backend ? If you got the secret key of the wallet owner. Like a truffle command or something ?

**Comment by AymericNoel** [comment]
To deploy contracts to a new network, you have to ad your own network in [truffle-config](https://github.com/AymericNoel/First_NFT_Dapp/blob/master/smart_contract/truffle-config.js) and then `truffle migrate --network *yourNetwork*`
